<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
<!--        <Nullable>enable</Nullable>-->
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    </ItemGroup>
    
    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
        <PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageReference Include="Keyfactor.Logging" Version="1.2.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Keyfactor.Platform.IPAMProvider" Version="1.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>